services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "yourpassword"
      - key: WEBHOOK_URL
        value: "https://your-render-url.com/"
      - key: GENERIC_TIMEZONE
        value: "America/Caracas"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      - key: N8N_DISABLE_UI
        value: "false"
      - key: N8N_DISABLE_PRODUCTION_MAIN_PROCESS
        value: "false"
